# Generated by Django 4.2.1 on 2023-05-27 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('state', models.CharField(max_length=100, verbose_name='Штат')),
                ('zip', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Почтовый индекс')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
            ],
        ),
    ]
