# Generated by Django 4.2.1 on 2023-05-27 15:45
import csv
import os

from django.db import migrations

from TruckSearcher import settings
from ..models import Location


def parse_csv_to_db(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, 'locations.csv'), 'r') as file:
        reader = csv.DictReader(file, delimiter=',')
        location_list = []
        for row in reader:
            location_list.append(
                Location(
                    city=row['city'],
                    state=row['state_name'],
                    zip=int(row['zip']),
                    lat=float(row['lat']),
                    lng=float(row['lng']),
                )
            )
        Location.objects.bulk_create(location_list, batch_size=900)


def delete_parsed_data(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, 'locations.csv'), 'r') as file:
        reader = csv.DictReader(file, delimiter=',')
        zip_list = []
        for row in reader:
            zip_list.append(int(row['zip']))
        for i in range(900, len(zip_list), 900):
            zip_list_part = zip_list[i-900: i]
            Location.objects.filter(zip__in=zip_list_part).delete()
            if len(zip_list) - i < 900:
                zip_list_part = zip_list[i:len(zip_list)]
                Location.objects.filter(zip__in=zip_list_part).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_zip'),
    ]

    operations = [
        migrations.RunPython(parse_csv_to_db, delete_parsed_data)
    ]
