# Generated by Django 4.2.1 on 2023-05-27 15:45
import csv
import os

from django.db import migrations

from TruckSearcher import settings
from ..models import Location


def parse_csv_to_db(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, 'locations.csv'), 'r') as file:
        reader = csv.DictReader(file, delimiter=',')
        for row in reader:
            location = Location(
                city=row['city'],
                state=row['state_name'],
                zip=int(row['zip']),
                lat=float(row['lat']),
                lng=float(row['lng']),
            )
            location.save()


def delete_parsed_data(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, 'locations.csv'), 'r') as file:
        reader = csv.DictReader(file, delimiter=',')
        for row in reader:
            Location.objects.get(zip=row['zip']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_zip'),
    ]

    operations = [
        migrations.RunPython(parse_csv_to_db, delete_parsed_data)
    ]
