# Generated by Django 4.2.1 on 2023-05-27 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_sign', models.CharField(max_length=5, unique=True, verbose_name='Регистрационный номер')),
                ('load_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inner_vehicles', to='location.location', verbose_name='Текущая локация')),
            ],
        ),
    ]
