# Generated by Django 4.2.1 on 2023-05-30 10:18
import random
import string

from django.db import migrations
import os
from TruckSearcher import settings
from location.models import Location
from vehicle.models import Vehicle


def create_default_vehicles(apps, schema_editor):
    vehicle_list = []
    with open(os.path.join(settings.BASE_DIR, 'vehicle_reg_sign_list.txt'), 'w') as file:
        for location in Location.objects.all()[:20]:
            reg_sign = str(random.randint(1000, 9999)) + random.choice(string.ascii_uppercase)
            file.write(reg_sign+'\n')
            vehicle_list.append(
                Vehicle(
                    reg_sign=reg_sign,
                    current_location=location,
                    load_capacity=round(float(random.randint(0, 1000) + random.random()), 1),
                )
            )
    Vehicle.objects.bulk_create(vehicle_list)


def delete_default_vehicles(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, 'vehicle_reg_sign_list.txt'), 'r') as file:
        vehicle_list = [row.strip('\n') for row in file.readlines()]
        print(vehicle_list)
        Vehicle.objects.filter(reg_sign__in=vehicle_list).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_vehicles, delete_default_vehicles)
    ]
